# Generated by Django 3.0.7 on 2020-06-16 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('profile_img', models.ImageField(upload_to='profile')),
                ('bio', models.CharField(max_length=10000)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary'), ('T', 'Transgender')], max_length=12)),
                ('weight_class', models.CharField(choices=[('43 kg', '94 lb'), ('47 kg', '103 lb'), ('52 kg', '114 lb'), ('53 kg', '116 lb'), ('57 kg', '125 lb'), ('59 kg', '130 lb'), ('63 kg', '138 lb'), ('66 kg', '145 lb'), ('72 kg', '158 lb'), ('74 kg', '163 lb'), ('83 kg', '182 lb'), ('84 kg', '185 lb'), ('84 kg+', '185 lb+'), ('93 kg', '205 lb'), ('105', '231 lb'), ('120', '264 lb'), ('120 kg+', '264 lb+')], max_length=7)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
