# Generated by Django 3.0.7 on 2020-06-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iEaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='age',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
