# Generated by Django 3.0.7 on 2020-06-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iEaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
