# Generated by Django 3.0.7 on 2020-06-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iEaccounts', '0002_auto_20200625_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_image/'),
        ),
    ]
