# Generated by Django 3.0.5 on 2020-05-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
